### ISSUE TITLE
Windows build doesn't work

### ISSUE THREAD

**Issue by Midnoclose** [NovaSquirrel/Mesen#15]
I followed the instructions in COMPILING.md, and I got these errors when launching the built Mesen.exe
![error 1](https://user-images.githubusercontent.com/24860483/103499267-4f273900-4dfc-11eb-9641-d996a20c427f.png)
![error 2](https://user-images.githubusercontent.com/24860483/103499271-50f0fc80-4dfc-11eb-9a35-cb8bfba275d2.png)

**Comment by NovaSquirrel** [comment]
You need to click "▶️Start" a second time after it gives that error. There's some weird quirk with the project where the first build doesn't work (but any build after that does), and I haven't looked into why that is or how to fix it yet.

I'll go add a note about this to COMPILING.md.

**Comment by Midnoclose** [comment]
It worked, thanks for the quick reply!
