### ISSUE TITLE
PPU viewer shows garbage in Super Mario Bros. 3

### ISSUE THREAD

**Issue by anonymous7002** [NovaSquirrel/Mesen#17]
![Mesen_pL4Bx3Qy90](https://user-images.githubusercontent.com/57062013/104763101-137e5e80-576e-11eb-8fb6-46302e9bc0cd.png)

**Comment by NovaSquirrel** [comment]
This is intended behavior. You give the PPU viewer a scanline number with `When emulation is running, show PPU data at scanline` and it renders everything with the status at that scanline. So if you want the map to look correct instead, you need to set it to a scanline that contains the map.

![image](https://user-images.githubusercontent.com/1865623/104781302-3c8ff680-5750-11eb-92d7-657bd89d1fec.png)

**Comment by anonymous7002** [comment]
When I pause the emulator, it goes on to show the same garbled mess. Unpausing fixes it.
