### ISSUE TITLE
[Feature request] Dev/nightly builds for mesen

### ISSUE THREAD

**Issue by JuanchoES** [NovaSquirrel/Mesen#26]
Since the link to the latest build is not working right now i would like to have nighly builds for this emulator, i dont know how to compile, sorry :S

**Comment by NovaSquirrel** [comment]
I think this is set up on the Mesen-S fork so I'll have to try and port it over to this one too. And it wouldn't hurt to do a release too.

**Comment by JuanchoES** [comment]
Hello again, sorry if i am bothering you but when is the dev builds gonna happen?

**Comment by NovaSquirrel** [comment]
[Right now!](https://github.com/NovaSquirrel/Mesen/actions/runs/829634408)
