### ISSUE TITLE
A couple of name suggestions for Mesen and Mesen-S

### ISSUE THREAD

**Issue by John-Enigma** [NovaSquirrel/Mesen#31]
I don't know if this fork and the Mesen-S fork are active, but I already have some name suggestions for these forks, if y'all are interested: Mesen++ for Mesen, and the same thing for Mesen-S, which would Mesen-S++.

What do you think?

**Comment by NovaSquirrel** [comment]
They're active in the sense that if a pull request comes in I will look at it and merge it, at least. I was thinking something like "Mesen Community Edition" myself

**Comment by John-Enigma** [comment]
Mesen CE & Mesen-S CE?

Alright. No problem.

Reason why I mentioned Mesen++ and Mesen-S++ was in reference to their codebase being built 
almost entirely on C++.
